services:
  portfolio_nextjs:
    container_name: portfolio_nextjs
    hostname: portfolio_nextjs
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app/portfolio-nextjs
    ports:
      - 3000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio_nextjs.rule=Host(`yerayboix.com`) || Host(`www.yerayboix.com`)"
      - "traefik.http.routers.portfolio_nextjs.entrypoints=websecure"
      - "traefik.http.routers.portfolio_nextjs.tls.certResolver=letsencrypt"
      - "traefik.http.services.portfolio_nextjs.loadbalancer.server.port=3000"


networks:
  dokploy-network:
    external: true
